# Generated by Django 5.2.5 on 2025-10-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child_selection", "0001_initial"),
        ("kidlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.AlterField(
            model_name="htmtrecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.AlterField(
            model_name="milkrecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.AlterField(
            model_name="foodrecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.AlterField(
            model_name="sleeprecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.AlterField(
            model_name="pooprecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.AlterField(
            model_name="peerecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.AlterField(
            model_name="temperaturerecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child_selection.child"
            ),
        ),
        migrations.DeleteModel(
            name="Child",
        ),
    ]
