# Generated by Django 5.2.5 on 2025-10-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child_selection", "0001_initial"),
        ("kidlog", "0002_alter_activity_child_alter_htmtrecord_child_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="activity_type",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="child",
        ),
        migrations.CreateModel(
            name="DiaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="child_selection.child",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ActivityType",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
