# Generated by Django 5.2.5 on 2025-10-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kidlog", "0003_remove_activity_activity_type_remove_activity_child_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryrecord",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
