# Generated by Django 5.2.5 on 2025-10-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kidlog", "0004_diaryrecord_summary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiaryRecord",
        ),
    ]
