# Generated by Django 5.2.5 on 2025-10-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("child_selection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("note", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="child_selection.child",
                    ),
                ),
            ],
        ),
    ]
